### ISSUE TITLE
Some problem with start X11

### ISSUE THREAD

**Issue by mad03day** [cvetaevvitaliy/stm32mp1-ubuntu#5]
Маю певні проблеми зі стартом x11, а саме з кадровим буфером. Чи не міг би ти поділитися як саме його запустити як у цьому відео: https://www.youtube.com/watch?v=BHgTgeLFGMI
![image](https://user-images.githubusercontent.com/71565506/168419971-7e29380d-46c5-4297-a329-9c29c8307b96.png)
![image](https://user-images.githubusercontent.com/71565506/168419998-daec175c-8acc-47f7-8550-390ef5c40c0a.png)

**Comment by cvetaevvitaliy** [comment]
Привіт!
Слава Україні 

Потрібно зібрати GPU драйвер, та скачати OpenGL з [https://github.com/STMicroelectronics/gcnano-binaries](https://github.com/STMicroelectronics/gcnano-binaries)

Будуть працювати і X11 а також Wayland 
Зараз я працюю з wayland, в нього набагато краще продуктивність

![image](https://user-images.githubusercontent.com/26421560/168420654-a886d033-3577-43e9-8e77-4d08412bfd06.jpeg)

**Comment by mad03day** [comment]
Чи можна попросити твої контакти для більш зручного спілкування у випадку чого?

**Comment by cvetaevvitaliy** [comment]
> Чи можна попросити твої контакти для більш зручного спілкування у випадку чого? 

Telegram @VITNIM
